# Generated by Django 3.1.7 on 2021-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0009_auto_20210410_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Categorias'),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Emprendedores'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del Producto', max_length=500, null=True, verbose_name='descripción'),
        ),
    ]
